### PR TITLE
standalone pose refinement and rig pose estimation

### PR DESCRIPTION
**Pull request by yocabon**
For the rig pose estimation, all the components are there in COLMAP, but they're not well put together. I tried assembling blocks and had to link directly to ceres/boost.

### CODE REVIEW

**Comment by Skydes** [comment]
1. I actually already have a branch that does rig pose estimation: https://github.com/Skydes/pycolmap/tree/rigs This does not require boost. Another difference is that I copied the estimator to use the pixel reprojection instead of the angular error. This should ideally be patched upstream in COLMAP.
2. Are the changes to setup.py related to the PR? Or just to Windows support?

**Comment by yocabon** [comment]
1. I didn't know, this might be a cleaner version of what I was trying to achieve (I've been sitting on this code for a while and decided to push it now since I'm about to do the same with the RansacLib and MultiCameraPose versions)
2. It's just windows support, I work on Windows and I just added it to make it easy to compile.

**Comment by yocabon** [comment]
about "had to link directly to ceres/boost." I didn't recall exactly why I had to do that, but now that I tried to compile your branch it's clear, I can't get it to compile, I'm getting  error LNK2019 unless I link them directly (probably something to do with vcpkg...) I'll try to clean that up before submitting again.

**Comment by Skydes** [comment]
It would still be nice to address the Windows compilation in a separate PR as some people have had some issues with it (see https://github.com/mihaidusmanu/pycolmap/issues/6) and neither @mihaidusmanu nor myself work with Win :)

**Pull request closed without merging**
