### PR TITLE
make number of LORANSAC iterations configurable by function argument

### PR DESCRIPTION
**Pull request by johnwlambert**
Currently hard-coded.

### CODE REVIEW

**Comment by johnwlambert** [comment]
@mihaidusmanu could you take a look at this when you get a chance? Although you're likely busy with CVPR, can be after that : - )

**Comment by mihaidusmanu** [comment]
Hey. Sorry for the delay - I think it's a good idea to expose these parameters and the PR looks good to me.

However, for consistency, we should also expose them for PnP / GPnP. In case you don't have time to deal with that, I can merge this and push a fix for the rest later in the week.

**Comment by mihaidusmanu** [comment]
Will push a fix for the rest in a bit!

**Comment by johnwlambert** [comment]
Thanks!

**Pull request merged**
